3services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sd2
    ports:
      - "3308:3306"      # MySQL exposed on localhost:3308
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
      - "8081:80"        # phpMyAdmin on http://localhost:8081
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: node index.js
    ports:
      - "3000:3000"      # App on http://localhost:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: sd2

volumes:
  db_data:
